spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myfair?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zxcasdqwe123
    type: com.alibaba.druid.pool.DruidDataSource
  web:
    resources:
      static-locations: classpath:/META-INF/resources,classpath:/resources/.classpath:/static/,classpath:/public/,file:${pictureFile.path-mapping}

server:
  port: 9090
  tomcat:
    max-http-form-post-size: 20971520

mybatis:
  mapper-locations: classpath:/mappers/*.xml

pictureFile:
  path: "D:/workspace-Java/Fair/myfair/src/main/resources/static/images"
  path-mapping: "/images/"

