spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myfair?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zxcasdqwe123
    type: com.alibaba.druid.pool.DruidDataSource
